import { useEffect,useState } from "react";
import { Link,useNavigate,useParams } from "react-router-dom";
import { ArrowLeft, Save } from "lucide-react";
import { jobsApi,companiesApi } from "../../api/services";
import { getErrorMessage } from "../../api/client";
import PageHeader from "../../components/common/PageHeader";
import useToast from "../../hooks/useToast";
import Toast from "../../components/common/Toast";
import Loader from "../../components/common/Loader";

const initial={title:"",description:"",location:"",company:"",requirements:"",job_type:"FULL_TIME",salary_min:"",salary_max:"",salary_currency:"$",category:"",tags:"",is_active:true};

export default function JobForm(){
 const {id}=useParams();const edit=Boolean(id);const navigate=useNavigate();const [form,setForm]=useState(initial),[companies,setCompanies]=useState([]),[loading,setLoading]=useState(edit),[saving,setSaving]=useState(false);const {toast,show}=useToast();
 useEffect(()=>{Promise.all([companiesApi.mine(),edit?jobsApi.detail(id):Promise.resolve({data:null})]).then(([c,j])=>{setCompanies(Array.isArray(c.data)?c.data:c.data.results||[]);if(j.data){const x=j.data;setForm({...initial,...x,tags:Array.isArray(x.tags)?x.tags.join(", "):x.tags||""})}}).catch(e=>show(getErrorMessage(e),"error")).finally(()=>setLoading(false))},[id]);
 function change(name,value){setForm(f=>({...f,[name]:value}))}
 async function submit(e){e.preventDefault();setSaving(true);try{const payload={...form,tags:form.tags?form.tags.split(",").map(x=>x.trim()).filter(Boolean):[]};if(!payload.company)delete payload.company;for(const k of ["salary_min","salary_max"])if(payload[k]==="")delete payload[k];if(edit)await jobsApi.update(id,payload);else await jobsApi.create(payload);show(edit?"Job updated":"Job created");setTimeout(()=>navigate("/recruiter/jobs"),500)}catch(e){show(getErrorMessage(e),"error")}finally{setSaving(false)}}
 if(loading)return <Loader full/>;
 return <div><Link className="back-link" to="/recruiter/jobs"><ArrowLeft size={16}/> Back to jobs</Link><PageHeader title={edit?"Edit job":"Post a new job"} subtitle={edit?"Update the job details and publishing state.":"Create a clear, complete opportunity for candidates."}/><form className="panel form job-form" onSubmit={submit}><div className="form-section"><h2>Job details</h2><div className="two-col"><label>Job title<input required value={form.title} onChange={e=>change("title",e.target.value)} placeholder="Senior Full Stack Engineer"/></label><label>Category<input value={form.category||""} onChange={e=>change("category",e.target.value)} placeholder="Software Engineering"/></label></div><div className="two-col"><label>Location<input required value={form.location} onChange={e=>change("location",e.target.value)} placeholder="Remote / Kochi / New York"/></label><label>Job type<select value={form.job_type||""} onChange={e=>change("job_type",e.target.value)}><option value="FULL_TIME">Full-time</option><option value="PART_TIME">Part-time</option><option value="CONTRACT">Contract</option><option value="INTERNSHIP">Internship</option></select></label></div><label>Company<select value={form.company||""} onChange={e=>change("company",e.target.value)}><option value="">Auto-select / no company</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Description<textarea required rows="8" value={form.description} onChange={e=>change("description",e.target.value)} placeholder="Describe the role, team and impact…"/></label><label>Requirements<textarea rows="7" value={form.requirements||""} onChange={e=>change("requirements",e.target.value)} placeholder="Required skills, qualifications and experience…"/></label></div><div className="form-section"><h2>Compensation & discovery</h2><div className="three-col"><label>Min salary<input type="number" value={form.salary_min??""} onChange={e=>change("salary_min",e.target.value)}/></label><label>Max salary<input type="number" value={form.salary_max??""} onChange={e=>change("salary_max",e.target.value)}/></label><label>Currency<input value={form.salary_currency||""} onChange={e=>change("salary_currency",e.target.value)}/></label></div><label>Tags<input value={form.tags||""} onChange={e=>change("tags",e.target.value)} placeholder="React, Django, PostgreSQL, Docker"/></label><label className="checkbox"><input type="checkbox" checked={Boolean(form.is_active)} onChange={e=>change("is_active",e.target.checked)}/> Publish as active job</label></div><div className="form-actions"><Link className="btn ghost" to="/recruiter/jobs">Cancel</Link><button className="btn primary" disabled={saving}><Save size={16}/>{saving?"Saving…":edit?"Save changes":"Publish job"}</button></div></form><Toast toast={toast}/></div>
}
