# Generated by Django 5.2.14 on 2026-09-17 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('jobs', '0001_initial'),
        ('resumes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationstatushistory',
            name='application',
        ),
        migrations.RemoveField(
            model_name='applicationstatushistory',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='recruiternote',
            name='application',
        ),
        migrations.RemoveField(
            model_name='recruiternote',
            name='recruiter',
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='resumes.resume'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('in_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview Scheduled'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='applied', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('job', 'candidate'), name='unique_application_per_job'),
        ),
        migrations.DeleteModel(
            name='ApplicationStatusHistory',
        ),
        migrations.DeleteModel(
            name='RecruiterNote',
        ),
        migrations.RemoveField(
            model_name='application',
            name='match_score',
        ),
    ]
