import { useEffect,useRef,useState } from "react";
import { FileText, Upload, Star, Trash2, Download, Plus, X } from "lucide-react";
import { resumesApi } from "../../api/services";
import { getErrorMessage } from "../../api/client";
import PageHeader from "../../components/common/PageHeader";
import Loader from "../../components/common/Loader";
import EmptyState from "../../components/common/EmptyState";
import useToast from "../../hooks/useToast";
import Toast from "../../components/common/Toast";

export default function Resumes(){
 const [items,setItems]=useState([]),[open,setOpen]=useState(false),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);const [form,setForm]=useState({title:"",skills:"",experience_years:"",is_default:false});const fileRef=useRef();const {toast,show}=useToast();
 async function load(){const {data}=await resumesApi.list();setItems(Array.isArray(data)?data:data.results||[])}
 useEffect(()=>{load().finally(()=>setLoading(false))},[]);
 async function submit(e){e.preventDefault();setSaving(true);try{const fd=new FormData();fd.append("title",form.title);fd.append("file",fileRef.current.files[0]);if(form.skills)fd.append("skills",form.skills);if(form.experience_years)fd.append("experience_years",form.experience_years);fd.append("is_default",form.is_default);await resumesApi.create(fd);show("Resume uploaded");setOpen(false);setForm({title:"",skills:"",experience_years:"",is_default:false});await load()}catch(e){show(getErrorMessage(e),"error")}finally{setSaving(false)}}
 async function setDefault(id){try{await resumesApi.setDefault(id);await load();show("Default resume updated")}catch(e){show(getErrorMessage(e),"error")}}
 async function remove(id){if(!confirm("Delete this resume?"))return;try{await resumesApi.remove(id);await load();show("Resume deleted")}catch(e){show(getErrorMessage(e),"error")}}
 return <div><PageHeader title="My resumes" subtitle="Keep your application-ready resumes organized." action={<button className="btn primary" onClick={()=>setOpen(true)}><Plus size={17}/> Add Resume</button>}/>{loading?<Loader/>:items.length?<div className="resume-grid">{items.map(r=><div className="resume-card" key={r.id}><div className="resume-icon"><FileText size={25}/></div><div className="resume-content"><div className="row-between"><h3>{r.title}</h3>{r.is_default&&<span className="default-pill"><Star size={12}/> Default</span>}</div><p>{r.skills||"Skills not specified"}</p><span className="muted">{r.experience_years??0} years experience</span><div className="resume-actions">{r.file&&<a className="btn ghost small" href={r.file} target="_blank" rel="noreferrer"><Download size={14}/> Open</a>}{!r.is_default&&<button className="btn ghost small" onClick={()=>setDefault(r.id)}><Star size={14}/> Set default</button>}<button className="icon-btn danger" onClick={()=>remove(r.id)}><Trash2 size={16}/></button></div></div></div>)}</div>:<EmptyState title="No resumes yet" text="Upload a resume so you can apply faster." action={<button className="btn primary" onClick={()=>setOpen(true)}>Upload resume</button>}/>}
 {open&&<Modal title="Upload resume" close={()=>setOpen(false)}><form className="form" onSubmit={submit}><label>Title<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="My Full Stack Resume"/></label><label>File<input required ref={fileRef} type="file" accept=".pdf,.doc,.docx"/></label><label>Skills<input value={form.skills} onChange={e=>setForm({...form,skills:e.target.value})} placeholder="Python, Django, React, PostgreSQL"/></label><label>Experience years<input type="number" min="0" value={form.experience_years} onChange={e=>setForm({...form,experience_years:e.target.value})}/></label><label className="checkbox"><input type="checkbox" checked={form.is_default} onChange={e=>setForm({...form,is_default:e.target.checked})}/> Set as default</label><button className="btn primary full-btn" disabled={saving}><Upload size={16}/>{saving?"Uploading…":"Upload Resume"}</button></form></Modal>}<Toast toast={toast}/></div>
}
function Modal({title,close,children}){return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal"><div className="modal-head"><h2>{title}</h2><button className="icon-btn" onClick={close}><X/></button></div>{children}</div></div>}
